# Generated by Django 6.0.6 on 2026-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead de Contato',
                'verbose_name_plural': 'Leads de Contato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LeadCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Cotação de Evento',
                'verbose_name_plural': 'Leads Cotação de Evento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LeadTrabalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Trabalhe Conosco',
                'verbose_name_plural': 'Leads Trabalhe Conosco',
                'ordering': ['-criado_em'],
            },
        ),
    ]
