"""
Django settings for website_fmc project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return

    for raw_line in dotenv_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")

        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fmc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website_fmc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'fmc.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'website_fmc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.getenv('DJANGO_STATIC_URL', '/static/')
STATIC_ROOT = BASE_DIR / os.getenv('DJANGO_STATIC_ROOT', 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']


FMC_PAGE_CACHE_TIMEOUT = int(os.getenv('FMC_PAGE_CACHE_TIMEOUT', '300'))

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'fmc-site-cache',
        'TIMEOUT': FMC_PAGE_CACHE_TIMEOUT,
    }
}


EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'nao-responda@example.com')
FMC_NOTIFY_EMAIL = os.getenv('FMC_NOTIFY_EMAIL', DEFAULT_FROM_EMAIL)


FMC_SITE = {
    'brand_name': os.getenv('FMC_BRAND_NAME', 'YOUR_BRAND_NAME'),
    'emergency_phone_display': os.getenv('FMC_PHONE_DISPLAY', '(00) 00000-0000'),
    'phone_digits': os.getenv('FMC_PHONE_DIGITS', '5500000000000'),
    'address': os.getenv('FMC_ADDRESS', 'YOUR_CITY/STATE'),
    'email': os.getenv('FMC_EMAIL', 'contato@example.com'),
    'facebook_url': os.getenv(
        'FMC_FACEBOOK_URL',
        'https://www.facebook.com/your-page',
    ),
    'whatsapp_url': os.getenv(
        'FMC_WHATSAPP_URL',
        'https://wa.me/5500000000000',
    ),
    'whatsapp_cta_url': os.getenv(
        'FMC_WHATSAPP_CTA_URL',
        'https://api.whatsapp.com/send/?phone=5500000000000&text=Ola+Empresa%21+Vim+pelo+site.&type=phone_number&app_absent=0',
    ),
    'whatsapp_quote_url': os.getenv(
        'FMC_WHATSAPP_QUOTE_URL',
        'https://api.whatsapp.com/send/?phone=5500000000000&text=Ola+Empresa%21+Gostaria+de+solicitar+um+Orcamento.&type=phone_number&app_absent=0',
    ),
    'instagram_url': os.getenv(
        'FMC_INSTAGRAM_URL',
        'https://www.instagram.com/your-profile',
    ),
    'copyright_year': os.getenv('FMC_COPYRIGHT_YEAR', '2026'),
    'designer': os.getenv('FMC_DESIGNER', 'YOUR_DESIGNER'),
    'cnpj': os.getenv('FMC_CNPJ', '00.000.000/0000-00'),
}
